### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by nikolap994** [Evil-Bees/Alertit#13]

**Comment by nikolap994** [comment]
@all-contributors please add @nikolap994 for infrastructure and code

**Comment by nikolap994** [comment]
https://github.com/all-contributors please add @cehicm for infrastructure and design

**Comment by nikolap994** [comment]
@all-contributors please add @cehicm for infrastructure and design

**Comment by nikolap994** [comment]
@all-contributors please add @maddy020 for code

**Comment by maddy020** [comment]
Thank you for appreciation

**Comment by nikolap994** [comment]
@all-contributors please add @BairamovAllaz for code

**Comment by nikolap994** [comment]
@all-contributors please add @canberkkoc1 for code

**Comment by nikolap994** [comment]
@all-contributors please add @ammarali0608 for code
