### ISSUE TITLE
Add Support For Google Sign in

### ISSUE THREAD

**Issue by nikolap994** [Evil-Bees/Alertit#16]
Upgrade Next Auth setup to include Google Sign in option.

https://next-auth.js.org/providers/google

**Comment by maddy020** [comment]
I am interested to work on this issue 
Please assign it to me.

**Comment by nikolap994** [comment]
You are welcome to do so :)

**Comment by maddy020** [comment]
Hey @nikolap994 
I have make some changes in the file but call back function is  not working properly
Can you help me out ?

**Comment by nikolap994** [comment]
Can you make pull request with changes so I can take a look ?

**Comment by nikolap994** [comment]
hey @maddy020 , I didn't hear from you, are you having a problem with opening PR ?

**Comment by maddy020** [comment]
Oh ! very sorry for late response 
Just creating a PR

**Comment by nikolap994** [comment]
The PR is merged, Thank you for you hard work. For first version I've disabled this feature but it will be used in later versions.

As a token of appreciations we've added you in the Readme. 
Feel free to take any other opened issue :)

**Comment by maddy020** [comment]
Thank you @nikolap994 for appreciation 
Also thanks to you for supporting beginners in open source projects
