### ISSUE TITLE
Add additional information on Monitors

### ISSUE THREAD

**Issue by nikolap994** [Evil-Bees/Alertit#20]
Right now we have only information regarding monitor status.
I would like to have statistical data such as:
- Response time (how fast website responded to check for uptime)
- Average Response (statistical info of all checks)
- Uptime in the past 24hours (from all checks in the past 24h how often site was up)
- Uptime in the last 30 days (from all checks in the past 30 days how often site was up)
- When will certificate expire (This looks like something we can use https://gabrieleromanato.name/nodejs-check-the-validity-of-a-website-ssl-certificate)

**Comment by BairamovAllaz** [comment]
Hi. I'd like to do this task.
I did little research about all task.
For getting response time of a website, I found a library called 'Morgan'. I'd like to talk about rest after assignment..

**Comment by nikolap994** [comment]
I've assigned task to you. Feel free to do however you want. 
If there is anything I can do to help, hit me up 👍🏻

**Comment by BairamovAllaz** [comment]
Hi started to work on task and I have a couple of question. I am working on approach, but I am not sure if it is a good approach. I am thinking about creating a function inside Cron class that will send request every minute or seconds and will save time as millisecond inside database, and also it will save the results to array inside database (or session I didn't decide yet). So I'd like to know if this is the right approach if it isn't I'd like to hear your solution or clarifications:)

**Comment by nikolap994** [comment]
We already have cron job that is configurable per Monitor. Each cron job will update data in the database and latest info will be there. Since we are looking into statistics, possible approach is to create new table in the database (Model) and copy the data there, something like:
- Monitor ID
- Latest Check
- Status
And when you want to display statistics you pull all data for Monitor ID and re-calculate statistics.

This shouldn't be too complicated, you can just extend current cronjob monitor update logic and add below it logic to update data in the new table (lets call it statistic). 

How does this sound to you ?
