### ISSUE TITLE
Update  Status Page Styling

### ISSUE THREAD

**Issue by nikolap994** [Evil-Bees/Alertit#21]
We have new Status page and search monitors page.
Following our overall styles, we would like to have similar styles done on Status and search page.

The pages can be found at following URLs:
http://localhost:3000/status
http://localhost:3000/status/6394eb28c13422f6251fb68e

Styling changes should be done for both PC and Mobile, since we use Tailwind it should not cause much problems.

**Comment by aanmeba** [comment]
Hi team, 
I'm looking into the page in my local server. It looks okay, in terms of font-size, spacing, color, or responsive design and uses Tailwind already. Could you specify what sort of styling should be done form this issue?

**Comment by nikolap994** [comment]
@cehicm can you recommend what should @aanmeba do ?

**Comment by cehicm** [comment]
HI @aanmeba, the /status page is okay now, but I thought there could be some stylistic improvements when displaying individual monitor info (ex: http://localhost:3000/status/6394eb28c13422f6251fb68e), not sure what they would be, just that it could look nicer. Maybe we could use [Uptime](https://github.com/upptime/upptime) or [Statuspage](https://www.atlassian.com/software/statuspage?&aceid=&adposition=&adgroup=143568471495&campaign=18821797113&creative=633332534059&device=c&keyword=uptime%20website%20tool&matchtype=e&network=g&placement=&ds_kids=p74147500777&ds_e=GOOGLE&ds_eid=700000001541417&ds_e1=GOOGLE&gclid=CjwKCAiA5sieBhBnEiwAR9oh2mZmsNM9VGLYZvUcXsvveQFUvfNyf01RbDM8gCl5teVPJhyV1Z-2bhoCWCoQAvD_BwE&gclsrc=aw.ds). Or anything else you come up with.

Please let me know if you have any further questions! :)

**Comment by aanmeba** [comment]
Hi @cehicm, thank you for getting back to me! If you'd like to improve the page style-wise, not functionality, I would love to take part in this task! I'd say I can make the page look like Uptime or something. Please let me know if it would work for you :)

**Comment by cehicm** [comment]
Yes, this task is about appearance and not functionality. Sure, you can take inspiration from Uptime, but please make sure to stay true to the existing design. Just create a pull request when you're done.  thanks! :)
