### ISSUE TITLE
Update Nav appereance after adding "Monitor Status"

### ISSUE THREAD

**Issue by cehicm** [Evil-Bees/Alertit#33]
We want to make the Navigations look better, on smaller screens in particular. Perhaps make the Status nav item stand out somehow as well.  Anything you can do to improve it, as long as it follows the current styles
![Screenshot_4](https://user-images.githubusercontent.com/25206355/212493545-5c7d9ce6-f127-48b9-9107-f07688934dec.png)
![Screenshot_5](https://user-images.githubusercontent.com/25206355/212493546-0a55d9df-403f-4ade-8b14-0d5cfc7f2e4f.png)

**Comment by Richie1972** [comment]
Submitting documents only (e.g. KYC pilot participants) or even being authenticated as the person in the submitted documents, (e.g. Yoti KYC’ed), is only part of the Pi KYC process. Additional checks such as name matching, previous violations of Pi’s terms of service and policies and regulatory compliance verification will need to be performed, all of which will constitute a pass of the Pi KYC. Generally, after a Pioneer has submitted their KYC documentation, it will need to go through a verification process, which involves verification of one’s identity and compliance with Pi Network’s Terms of Service. For Pioneers that pass this verification process, their Pi balances will become transferable and get transferred to their Mainnet wallets in regular batches.

**Comment by vikssevishnu** [comment]
Hi, 
I would like to contribute for this issue. I thought I could check with you if the below screen shot is ok, 
![AlertIt](https://user-images.githubusercontent.com/24762559/214193395-c87bf402-ca45-49ef-b778-45c8dc8637a3.PNG)

**Comment by nikolap994** [comment]
Can you open the PR so @cehicm can review it ? 👍🏻

**Comment by vikssevishnu** [comment]
Sure I can do that. I haven't made the changes yet. Did some quick css changes and wanted to understand if the above image is something you are expecting.

**Comment by cehicm** [comment]
Please make sure to use Tailwind, as specified in the project.

**Comment by vikssevishnu** [comment]
Sure. I have submitted a pull request. Please check and let me know.
