### ISSUE TITLE
Update Login / Signup page Responsive

### ISSUE THREAD

**Issue by nikolap994** [Evil-Bees/Alertit#34]
Responsive styles should be updated on Login / Signup page.
Here is preview of the issue:
![212525124-08375767-aadb-446f-8a45-c1db08c4bd9f](https://user-images.githubusercontent.com/25112021/212539074-f9887292-14e9-41d7-a4e5-a2fe90b265f3.png)

**Comment by ammarali0608** [comment]
![image](https://user-images.githubusercontent.com/89630572/212558652-e56e711e-b702-409d-a019-3255254b6d0e.png)
![Screenshot from 2023-01-15 23-01-53](https://user-images.githubusercontent.com/89630572/212558663-89a8ad7d-8a1c-4356-b1b1-3d16a3b52443.png)

Responsiveness of the login page has been resolved
