### ISSUE TITLE
Create Register and Login page

### ISSUE THREAD

**Issue by nikolap994** [Evil-Bees/Alertit#4]
I've already added some authentication for login and basic forms but this is far from looking okay.  Can you "gamify" sign up process ? Those type of sign up pages are looking good nowadays and seems like they do the great job.

- Input validation
- Redirect to Dashboard
- Sign up; Animation: first the screen is split 60-40%, when form is active (clicked, focused), width is 30~40-60~70% (needs to be tested out, so it's not too jumpy); 
- Log in page
- Animate login
- Forgotten password page
- Responsive
- Register passwords need to match

**Comment by macck7** [comment]
After pressing signup button they will redireted to login page (I have added this feature)
