### ISSUE TITLE
Sign up button in register.js is not showing.

### ISSUE THREAD

**Issue by infilev** [Evil-Bees/Alertit#44]
## There has been issue regarding the sign up button in the register.js file 
- Firstly the sign up button is not showing for laptop size screen(in my laptop) even after scrolling the cursor.

![issue1!](https://user-images.githubusercontent.com/107412360/215157834-1c0ef52e-68e1-4d09-af97-c89400275a12.png)

-  Secondly, it does shows up during **inspect** for smaller resolution.  

![issue2!](https://user-images.githubusercontent.com/107412360/215158006-6a1ea964-b1f6-4314-964a-44e7de0b7a2f.png)

**Comment by cehicm** [comment]
Thanks for the heads up! If you'd like to address the issue you can open a new pull request.

**Comment by infilev** [comment]
I am working on it.

**Comment by infilev** [comment]
Hello,  I have done the changes and opened the pull request, please review it.
