### ISSUE TITLE
Add  public Status Page for selected Monitor

### ISSUE THREAD

**Issue by nikolap994** [Evil-Bees/Alertit#8]
We would like to have a Status page that could be a public link, sharable to other users or even posted on the site which we are monitoring. It would show uptime status for the site, percentage of uptime and info about  who to contact if the site is down.

Feel free to add anything else you would like. This issue is open to claim.

**Comment by BairamovAllaz** [comment]
Hey, I really like to be a part of your project. I don't have much NextJs experience, but I believe I can handle it:). I want to start with this task. Could you please give me a little bit more information like design, and what "does uptime status" and "percentage of uptime"? Thanks in advance..

**Comment by nikolap994** [comment]
Hello, thank you for showing interest. The idea is that logged in users can add monitor (site they are observing for uptime) and create share link to show status page of that monitor. Something like in case our site is down, check this page to confirm that it's us. The status page for the first version can show information  like last check for uptime, status of the monitor and site name, later on we will expand this to show how often site goes down and add percetages.
